# Generated by Django 2.1.4 on 2018-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
