# Generated by Django 2.1.4 on 2018-12-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_query_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.IntegerField(default=1),
        ),
    ]
