# Generated by Django 2.1.4 on 2018-12-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0003_auto_20181225_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='sys_conf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='team_assigned_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='complain.team'),
        ),
    ]
